# Generated by Django 4.2.9 on 2024-09-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantorder',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
