# Generated by Django 4.2.9 on 2026-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menucategory_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
