global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'notification-service'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'notification-service:8003' ]