server.name: kibana
server.port: 5601
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
#
elasticsearch.username: kibana_system
elasticsearch.password: "admin"  # If security is enabled

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true