input {
  #beats {
  #  port => 5044 # This should match the port you configured in your Django app
  #  codec => json
  #}

  tcp {
    port => 5044 # This should match the port you configured in your Django app
    codec => json_lines # could be json
  }
}

filter {
  # Add any filters here if needed
  # For example, to parse JSON logs:
  # json {
  #   source => "message"
  # }
  if [logger] == "django.utils.autoreload" {
    drop { }
  }
  if [message] =~ /Watching for file changes/ {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "kibana_system"
    password => "admin"
    index => "django-logs-%{+YYYY.MM.dd}" # could be index => "auth-service-%{+YYYY.MM.dd}"
  }
}
